name: release
on: 
  push:
    branches:
      - master
jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build binary
        run:   docker run --rm -u root -v `pwd`:/home/rust/src ekidd/rust-musl-builder cargo build --release
      - name: create release 
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/x86_64-unknown-linux-musl/release/itt-bot
